<?php
$renderCartLine = function ($line, $level = 0) use (&$renderCartLine) {
    $str = str_repeat('-', $level) . ' ';
    $str .= $line->getItem()->getDescription() . ' | ' . $line->getQuantity() . ' @ $' . $line->getPrice();
    $str .= "<br />";

    foreach ($item->getLineItems() as $c) {
        $str .= $renderCartLine($c, $level+1);
    }

    return $str;
};

foreach ($cart->getLineItems() as $i) {
    echo $renderCartLine($i) . "<br />";
}
